Modifications pour que l'installation fonctionne

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,125 +1,157 @@
 #!/bin/bash
 
-source /usr/share/yunohost/helpers
-source ./_common
-source .fonctions
-set -eu
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-# Retrieve app id
+source .fonctions
+source /usr/share/yunohost/helpers
+
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+ynh_check_error # Active trap pour arrêter le script si une erreur est détectée.
+
+#=================================================
+# RETRIEVE ARGUMENTS FROM THE MANIFEST
+#=================================================
+
+domain=$YNH_APP_ARG_DOMAIN
+path=$YNH_APP_ARG_PATH
+admin_prestashop=$YNH_APP_ARG_ADMIN
+language=$YNH_APP_ARG_LANGUAGE
+#multisite=$YNH_APP_ARG_MULTISITE
+is_public=$YNH_APP_ARG_IS_PUBLIC
+db_pwd=$YNH_APP_ARG_PASSWD
+email=$YNH_APP_ARG_EMAIL
+
 app=$YNH_APP_INSTANCE_NAME
 
-# Retrieve arguments
-domain=$1
-path=$2
-is_public=$3
-user=$4
-passwd=$5
-email=$6
+#=================================================
+# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
+#=================================================
 
-script_dir=$PWD
-
-# Vérifie que les variables ne sont pas vides.
 CHECK_VAR "$app" "app name not set"
-CHECK_VAR "$script_dir" "script_dir not set"
+CHECK_USER "$admin_prestashop"
+CHECK_PATH
+CHECK_DOMAINPATH
+CHECK_FINALPATH
 
-CHECK_PATH	# Vérifie et corrige la syntaxe du path.
-CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.
+#=================================================
+# STORE SETTINGS FROM MANIFEST
+#=================================================
 
-CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.
+ynh_app_setting_set $app domain $domain
+ynh_app_setting_set $app path $path
+ynh_app_setting_set $app admin $admin_prestashop
+ynh_app_setting_set $app is_public $is_public
+ynh_app_setting_set $app language $language
+ynh_app_setting_set $app db_pwd $db_pwd
+ynh_app_setting_set $app email $email
+#ynh_app_setting_set $app multisite $multisite
 
-# Install dependency to convert tracks to a readable format for the browser
-sudo apt-get update
-sudo apt-get -y -qq install php5-mysql
+#=================================================
+# CREATE A SQL BDD
+#=================================================
 
-# Check password strength
-[[ ${#passwd} -gt 5 ]] || ynh_die \
-"The password is too weak, it must be longer than 5 characters"
+db_name=$app
+db_user=$app
+db_pwd=$(ynh_string_random)
+ynh_mysql_create_db "$db_name" "$db_user" "$db_pwd"
+ynh_app_setting_set "$app" db_name "$db_name"
+ynh_app_setting_set "$app" db_pwd "$db_pwd"
+ynh_app_setting_set "$app" db_user "$db_user"
 
-# Save app settings
-user="$app"
-ynh_app_setting_set "$app" is_public "$is_public"
-ynh_app_setting_set "$app" password "$passwd"
-ynh_app_setting_set "$app" user "$user"
+#=================================================
+# Crée le repertoire de destination et check les permissions
+#=================================================
+sudo mkdir "$final_path"
+sudo chown -R www-data: $final_path
 
-# Initialize database as needed
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
 
-dbname=$app
-dbuser=$app
-dbpass=$(ynh_string_random)
-ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
+ynh_app_setting_set $app final_path $final_path
+SETUP_SOURCE  "prestashop_1.7.0.5.zip" # Télécharge la source, décompresse et copie dans $final_path
 
-# Store the database access
-echo -e "# MySQL Database"
+#=================================================
+# Set /etc/hosts
+#=================================================
+
+echo -e "127.0.0.1 $domain #PRESTASHOP" | sudo tee -a /etc/hosts
 
 
-# Remove trailing "/" for next commands
-if [[ ! "$path" == "/" ]]; then
-    path=${path%/}
-fi
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
 
-# Copy files to the right place
-final_path=/var/www/$app
-extract_source
-SUDO unzip $final_path/prestashop.zip $final_path/prestashop
-sudo mv $final_path/prestashop/* $final_path/
-sudo rm -rf $final_path/prestashop
+sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
+sudo sed -i "s@__PATHTOCHANGE__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
+sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf
+sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/$app.conf
 
-pushd $final_path/install/
-sudo php index_cli.php install \
-       --db_server=localhost \
-       --db_user=$dbuser \
-       --db_password=$dbpass \
-       --db_name=$dbname \
-       --db_driver=amysqli \
-       --db_port=3306 \
-       --lastname=$user \
-       --password=$passwd \
-       --email=$email \
-       --domain=$domain$path \
-       --prefix=_ps_
-  
-popd
- 
 
-# file owned by www-data before checking permissions
-sudo chown www-data:www-data $final_path -R
+#=================================================
+# SETUP SSOWAT
+#=================================================
 
-# Files owned by root, www-data can just read
-sudo chmod 0775 $final_path/config/ -R
-sudo chmod 0775 $final_path/cache/ -R
-sudo chmod 0775 $final_path/mails/ -R
-sudo chmod 0775 $final_path/log/ -R
-sudo chmod 0775 $final_path/img/ -R
-sudo chmod 0775 $final_path/modules/ -R
-sudo chmod 0775 $final_path/override/ -R
-sudo chmod 0775 $final_path/themes/default/lang/ -R
-sudo chmod 0775 $final_path/themes/default/pdf/lang/ -R
-sudo chmod 0775 $final_path/themes/default/cache/ -R	
-sudo chmod 0775 $final_path/translations/ -R
-sudo chmod 0775 $final_path/upload/ -R
-sudo chmod 0775 $final_path/download/ -R
-sudo chmod 0775 $final_path/extensions/ -R
-sudo chmod 0775 $final_path/resources/ -R
-sudo chmod 0775 $final_path/sitemap.xml
-
-# set database configuration
-sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
-
-# Modify Nginx configuration file and copy it to Nginx conf directory
-sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
-sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
-nginxconf=/etc/nginx/conf.d/$domain.d/$app.conf
-sudo cp ../conf/nginx.conf $nginxconf
-sudo chown root: $nginxconf
-sudo chmod 600 $nginxconf
-
-sudo yunohost app setting $app is_public -v "$is_public"
 if [ "$is_public" = "Yes" ];
 then
-  sudo yunohost app setting $app unprotected_uris -v "/"
+  sudo sed -i "s@#--PRIVATE--@@g" /etc/nginx/conf.d/$domain.d/$app.conf
 fi
 
-sudo rm -rf /var/www/$app/install/
+#=================================================
+# PHP-FPM CONFIGURATION
+#=================================================
 
-sudo service nginx reload
+POOL_FPM
+
+#=================================================
+# Option de l'applications
+#=================================================
+
+db_md5=$(echo $db_pwd | md5sum | awk '{print $1}')
+db_sha=$(echo $db_pwd | openssl dgst -sha1 -hmac "key" | awk -F'= ' {'print $2'})
+language="$(echo $language | head -c 2)"
+
+#=================================================
+# Changer les informations de la tables 
+#=================================================
+
+# Charger la structure des tables dans la base.
+# mysql --debug-check -u $db_user -p$db_pwd $db_user < ../conf/sql/prestashop.sql
+
+#=================================================
+# Donne un accès public pour curl
+#=================================================
+
+ynh_app_setting_set $app unprotected_uris "/"
+
+#=================================================
+# Régénère la configuration de SSOwat
+#=================================================
+
 sudo yunohost app ssowatconf
+
+#=================================================
+# Reload Nginx and regenerate SSOwat conf
+#=================================================
+sudo service php5-fpm restart
+sudo service nginx reload
+
+if [ "$is_public" = "No" ];
+then
+  # Retire l'accès public
+  ynh_app_setting_delete $app unprotected_uris
+  sudo yunohost app ssowatconf
+fi
+
+#=================================================
+# Nettoyer hosts
+#=================================================
+
+sudo sed -i '/#PRESTASHOP/d' /etc/hosts
